### ISSUE TITLE
[E2B-388] [E2B-366] Add `run_code` and `run_shell` methods (Python SDK)

### ISSUE THREAD

**Issue by jakubno** [e2b-dev/e2b#160]
<sub>From [SyncLinear.com](https://synclinear.com) | [E2B-366](https://linear.app/e2b/issue/E2B-366/add-run-code-and-run-shell-methods-python-sdk)</sub>

<sub>[E2B-388](https://linear.app/e2b/issue/E2B-388/[e2b-366]-add-run-code-and-run-shell-methods-python-sdk)</sub>

**Comment by mlejva** [comment]
Done but without `run_shell` for now. 
Instead, we can add "Bash" as a runtime to `run_code`.
