### ISSUE TITLE
[E2B-389] [E2B-365] Add `runCode` and `runShell` in JS SDK

### ISSUE THREAD

**Issue by jakubno** [e2b-dev/e2b#161]
<sub>From [SyncLinear.com](https://synclinear.com) | [E2B-365](https://linear.app/e2b/issue/E2B-365/add-runcode-and-runshell-in-js-sdk)</sub>

<sub>[E2B-389](https://linear.app/e2b/issue/E2B-389/[e2b-365]-add-runcode-and-runshell-in-js-sdk)</sub>

**Comment by mlejva** [comment]
Done but without `runShell` for now. 
Instead, we can add "Bash" as a runtime to `runCode`.
