### ISSUE TITLE
"Failed to fetch" when submitting any form

### ISSUE THREAD

**Issue by Kav-K** [e2b-dev/e2b#17]
**Describe the bug**
Starting the app with the README docker instructions or the local development instructions leads to "failed to fetch" on login attempts or when submitting any form like the registration form as well. Ubuntu 20, python3.11, node 16.15

![4CAA5679-D8B5-4E1A-9B0D-A90F5C41A901](https://user-images.githubusercontent.com/21161101/230743732-75a67224-1c6e-4078-bb94-843d8ad1e988.png)
![3EE8ACC3-F018-45AD-906B-50CFED8651DF](https://user-images.githubusercontent.com/21161101/230743733-0683c442-1750-4dab-9645-94888d76317d.png)
No error output on chrome dev tools console 

**To Reproduce**
Start the app and attempt to login 

**Expected behavior**
Login form to be submitted correctly

**Comment by ValentaTomas** [comment]
Can you show us the browser console logs here too?

**Comment by Kav-K** [comment]
Hey, last I checked there were no browser logs when this error happened

**Comment by mlejva** [comment]
Hey @Kav-K, was there any error during the [get started](https://github.com/e2b-dev/e2b#get-started) guide? Can you share the full terminal output for the get started guide?

**Comment by ValentaTomas** [comment]
Hey @Kav-K , there is a new update on `master` - we are now proxying all requests so a lot of network issues should be now resolved.

**Comment by Kav-K** [comment]
Thanks! I'll try out the latest changes soon

**Comment by ValentaTomas** [comment]
@Kav-K is it working now?

**Comment by Kav-K** [comment]
Yeah! Sorry, will close this now
