### ISSUE TITLE
[E2B-396] The `stdout` or `stderr` of a process is sometimes not returned full

### ISSUE THREAD

**Issue by mlejva** [e2b-dev/e2b#170]
We investigated this with @ValentaTomas and found a race condition in our infrastructure in the `envd`.

There are 3 goroutines on the backend:

1. scanning stdout pipe
2. scanning stderr pipe
3. waiting for the process to finish

The last goroutine sometimes finishes faster than the first two and unsubscribes all the frontend listeners to the process.

```

Solved by waitgroup for the stdout and stderr → then wait for process (should not be called before pipes finish).
```

<sub>From [SyncLinear.com](https://synclinear.com) | [E2B-396](https://linear.app/e2b/issue/E2B-396/the-stdout-or-stderr-of-a-process-is-sometimes-not-returned-full)</sub>

**Comment by ValentaTomas** [comment]
I added code that should fix this to devbookd - @jakubno is now also fixing the homedir, bashrc,.. problems so the new templates rebuild should have the fix.
