### ISSUE TITLE
[E2B-403] When you click the "copy" button in docs code snippets, it also copies the `$HighlightLine` comment

### ISSUE THREAD

**Issue by mlejva** [e2b-dev/E2B#178]
<sub>From [SyncLinear.com](https://synclinear.com) | [E2B-403](https://linear.app/e2b/issue/E2B-403/when-you-click-the-copy-button-in-docs-code-snippets-it-also-copies)</sub>

**Comment by TusharRGupta** [comment]
can you assign me this issue?

**Comment by TusharRGupta** [comment]
Yes ,sure

**Comment by mlejva** [comment]
Assigned and looking forward to your PR!

**Comment by mlejva** [comment]
Hey @TusharRGupta how is this issue going?
