### ISSUE TITLE
Release an AppImage or Docker image?

### ISSUE THREAD

**Issue by eval-exec** [e2b-dev/e2b#18]
**Is your feature request related to a problem? Please describe.**
I think build `e2b` from source code is not easy, would you like to build an AppImage or docker image to easily run `e2b`?
**Describe the solution you'd like**
Build AppImage and docker image, and put them on e2b repo's Release page.
**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by ValentaTomas** [comment]
With the new [getting started](https://github.com/e2b-dev/e2b#get-started) it should be just one command (`npm run start`) in the pulled repo - even if we built the Docker image you would have to start Supabase, download the Compose file and start the Docker.

There could be some potential improvement if we built our Docker images and integrated starting the Supabase into our compose though.

**Comment by eval-exec** [comment]
Thank you.

**Comment by eval-exec** [comment]
Thank you.

**Comment by eval-exec** [comment]
But I get an error after I run `npm start` on https://github.com/e2b-dev/e2b/tree/5e5d8eb1bbaf4eb801c6de4e7130ca92052a0bfc

[c.txt](https://github.com/e2b-dev/e2b/files/11220500/c.txt)

**Comment by eval-exec** [comment]
> Oh, you need to set the env vars as instructed in the [get started guide](https://github.com/e2b-dev/e2b#1-add-env-var). We will introduce `npm start` without the need for setting env vars with the next PR merge but if you are on `main` you have to add them for now.

Thank you :heart:
