### ISSUE TITLE
Help: I don't know how should i add a url

### ISSUE THREAD

**Issue by kokofixcomputers** [e2b-dev/E2B#211]
How do i add into the chatgpt plugins i see a E2B Server URL field when i try to install the plugin but where do i get my url? i don't see how in the docs

**Comment by ValentaTomas** [comment]
Hey @kokofixcomputers, I'm not completely sure what is your use case. Are you trying to use E2B as a ChatGPT plugin? If so we have a separate repository (https://github.com/e2b-dev/llm-code-interpreter) for that.

If you want to use it differently, can you please describe how in more detail?

**Comment by kokofixcomputers** [comment]
Oh, thank you I was looking for the plugin! But chatgpt never uses it it just start self reflection and say the plugin is unavailable

**Comment by ValentaTomas** [comment]
That sometimes happend to me too but I was often able to persuade it that it can actually do what I want. Maybe changing the prompts inside the plugin repo could help?
