### ISSUE TITLE
[🛑 Assigned]  ✴️  Integrate E2B into AutoGen

### ISSUE THREAD

**Issue by tizkovatereza** [e2b-dev/E2B#241]
To see all bounties and learn everything about the bounty program, go [HERE](https://github.com/e2b-dev/E2B/issues/242).

## Description

AutoGen is a framework that enables the development of LLM applications using multiple agents that can converse with each other to solve tasks.  Integrating E2B means using [E2B sandboxes](https://e2b.dev/docs/sandbox/overview) as a runtime environment for the agents created with AutoGen.

## Useful links
Each integration works differently, and it's up to you to think of the necessary steps. These resources might help you better understand AutoGen and E2B.
- [AutoGen GitHub](https://github.com/microsoft/autogen)
- [AutoGen's new option for agents to add functions](https://github.com/microsoft/autogen/blob/ff37254abe504901f024db451c80debb63780d19/notebook/agentchat_inception_function.ipynb)
- [E2B Docs](https://e2b.dev/docs)
- [Microsoft's AutoGen - A guide to code-executing agents](https://e2b.dev/blog/microsoft-s-autogen)

### Existing integrations
For inspiration and to understand how the integrations may work, see:
- [E2B Sandbox used with OpenAI Assistants API](https://e2b.dev/docs/llm-platforms/openai)
- [Custom Data Analysis Sandbox for LangChain](https://python.langchain.com/docs/integrations/tools/e2b_data_analysis?ref=build-ai-data-analyst-with-langchain-and-e2b)
- [E2B as a tool for code execution in Superagent](https://github.com/homanp/superagent/blob/54a5da97f53c06bd7cc3ba66eb88685e7837e666/libs/superagent/app/tools/e2b.py#L11)

**Comment by tizkovatereza** [comment]
Hello Tushar,
Yes, I assigned you there if it is more convenient for you to communicate under the issue on GitHub. :) We can also jump on a quick call during the week if you feel like discussing the integration with us.

Just FYI, we have multiple applicants for each bounty, but you are the first who responded to AutoGen, so you have a priority for that.


Let me know if you have any other questions!


T.

**Comment by Vayras** [comment]
Okay , I will hop on to discord as well and we can discuss the integration for this issue, looking forward to working on this.

**Comment by tizkovatereza** [comment]
The bounty program has undergone changes and this is no longer the way to apply for paid contributions.
