### ISSUE TITLE
✴️ Integrate E2B into Rivet

### ISSUE THREAD

**Issue by tizkovatereza** [e2b-dev/E2B#244]
To see all bounties and learn everything about the bounty program, go [HERE](https://github.com/e2b-dev/E2B/issues/242).

## Description

Rivet is a visual programming environment for building AI agents with LLMs. You can iterate on your prompt graphs in Rivet, then run them directly in your application.
Integrating E2B means using [E2B sandboxes](https://e2b.dev/docs/sandbox/overview) as a runtime environment for the agents created with Rivet.

## Useful links
Each integration works differently, and it's up to you to think of the necessary steps. These resources might help you better understand Rivet and E2B.
- [Rivet docs](https://rivet.ironcladapp.com/docs)
- [E2B docs](https://e2b.dev/docs)

### Existing integrations
For inspiration and to understand how the integrations may work, see:
- [E2B Sandbox used with OpenAI Assistants API](https://e2b.dev/docs/llm-platforms/openai)
- [Custom Data Analysis Sandbox for LangChain](https://python.langchain.com/docs/integrations/tools/e2b_data_analysis?ref=build-ai-data-analyst-with-langchain-and-e2b)
- [E2B as a tool for code execution in Superagent](https://github.com/homanp/superagent/blob/54a5da97f53c06bd7cc3ba66eb88685e7837e666/libs/superagent/app/tools/e2b.py#L11)

**Comment by rishi-raj-jain** [comment]
@tizkovatereza can I be assigned this?

**Comment by tizkovatereza** [comment]
Hello @rishi-raj-jain, can you please first share, at least on high level, what your approach would be? We would like to check that the approach makes sense and is possible, before you start devoting your time. :) 

Feel free to jump on our discord or email us and share what's your thinking about this and if you have certain plan for that bounty. (It doesn't have to be in big detail, just high level).

Thank you!

Tereza
