### ISSUE TITLE
Add timeout for `process.wait()`

### ISSUE THREAD

**Issue by jakubno** [e2b-dev/E2B#253]
If the process doesn't end in reasonable time, it usually means there's some issue and the process could be stuck or running infinitely.

<sub>[E2B-439](https://linear.app/e2b/issue/E2B-439/add-timeout-for-processwait)</sub>

**Comment by ValentaTomas** [comment]
The process (command) request timeout and wait timeout (how long the process itself can run) are separated arguments in the new beta SDK.
