### ISSUE TITLE
[E2B-441] Building custom sandbox fails when `e2b.Dockerfile` is in `.dockerignore`

### ISSUE THREAD

**Issue by mlejva** [e2b-dev/E2B#255]
**Describe the bug**
When building a custom sandbox and using `.dockerignore`, it fails if the Dockerfile for the sandbox is in `.dockerignore`.
However, it's completely valid to put Dockerfile in `.dockerignore` when using Docker. 

We should probably behave the same.

**To Reproduce**

1. Run `e2b init`
2. Put `e2b.Dockerfile` to `.dockerignore`
3. Run `e2b build`

**Expected behavior**
The build should work.

<sub>[E2B-441](https://linear.app/e2b/issue/E2B-441/building-custom-sandbox-fails-when-e2bdockerfile-is-in-dockerignore)</sub>

**Comment by ValentaTomas** [comment]
This is probably caused by a bug in CLI - when we are packaging the local Docker context we are using `.dockerignore` to exclude files in the context, but if the used dockerfile is not named `Dockerfile` we incorrectly package this file even though we are loading the file separately.

**Comment by jakubno** [comment]
Fixed by #295
