### ISSUE TITLE
[E2B-442] Using `sandbox.download_file` on an empty file throws error

### ISSUE THREAD

**Issue by ValentaTomas** [e2b-dev/E2B#256]
When you try to download an empty file from the sandbox you will get an error:

```py
from e2b import CodeInterpreter


sandbox = CodeInterpreter()
sandbox.cwd = "/home"  

proc2 = sandbox.process.start("sudo touch /home/file.txt",on_stdout=print,on_stderr=print)
proc2.wait()
process_cwd = sandbox.process.start("ls",on_stdout=print,on_stderr=print)
file_in_bytes = sandbox.download_file("/home/file.txt")  

with open("file.txt", "wb") as f:  
    f.write(file_in_bytes) 
```

```
Exception: Failed to download file '/home/file.txt'. Internal Server Error Error reading file: EOF
```

`sandbox.filesystem.read` should work without problems until we fix the file download.

<sub>[E2B-442](https://linear.app/e2b/issue/E2B-442/using-sandboxdownload-file-on-an-empty-file-throws-error)</sub>

**Comment by ValentaTomas** [comment]
We should check if the `upload_file` works with empty files too.

**Comment by vaibhavard** [comment]
Still this issue persists

**Comment by jakubno** [comment]
This should be fixed, but you'll have to rebuild your sandbox template.
