### ISSUE TITLE
ImportError: cannot import name 'Sandbox' from 'e2b'

### ISSUE THREAD

**Issue by qingpowuwu** [e2b-dev/E2B#271]
**Describe the bug**
ImportError: cannot import name 'Sandbox' from 'e2b'

**To Reproduce**
After I run the .py code:
```
# 1. Import E2B
from e2b import Sandbox

# 2. Get your Sandbox session
sandbox = Sandbox()

# 3. Close the sandbox once done
sandbox.close()
```
I got this error, this is the screenshot:
![1703317055396](https://github.com/e2b-dev/E2B/assets/140480316/e1e64934-0ead-4deb-a2ad-5c78a0ea8e9d)

I also could not find the Sandbox from the e2b source file, this is my screenshot:
![1703317135486](https://github.com/e2b-dev/E2B/assets/140480316/c4c55891-1f70-4da4-ade3-f689c7bc41dc)

**Desktop (please complete the following information):**

- OS: iOS 12.5

Can you helps me please?

**Comment by jakubno** [comment]
Hi @qingpowuwu, you have old version of SDK, please upgrade with `pip install e2b --upgrade`

**Comment by qingpowuwu** [comment]
Thanks a lot!!!
