### ISSUE TITLE
https://e2b.dev/docs?error=server_error&error_code=500&error_description=Database+error+saving+new+user#error=server_error&error_code=500&error_description=Database+error+saving+new+user

### ISSUE THREAD

**Issue by KompasAI** [e2b-dev/E2B#279]
when click sign in or sign up throw this error the browser have any error  could you help me
https://e2b.dev/docs?error=server_error&error_code=500&error_description=Database+error+saving+new+user#error=server_error&error_code=500&error_description=Database+error+saving+new+user

**Comment by jakubno** [comment]
Hi @KompasAI, thanks for reporting this. It was a mistake on our side, it should be fixed now. I am sorry for the inconvenience.

**Comment by ValentaTomas** [comment]
This issue should be fixed.
