### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by SnoopyDevelops** [e2b-dev/e2b#28]
**Describe the bug**
TypeError: Failed to fetch

**To Reproduce**
1. Setup environment for development 
2. Start the server
3. Create project
4. Run

**Screenshots**
![image](https://user-images.githubusercontent.com/54778084/232953556-bd0ec454-e213-4ada-9aab-3eab8dbed95a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
I think this error is related with command difference between OS
```
'export' is not recognized as an internal or external command,
operable program or batch file.
Process on port 49160 killed
```

**Comment by SnoopyDevelops** [comment]
1. There were no issue to start with guide using docker.
2. I used dev setup guide.
3. terminal output
![image](https://user-images.githubusercontent.com/54778084/233083361-5a77d2c9-fb02-4382-b4b1-a3ad1d8ac900.png)
4. browser console
![image](https://user-images.githubusercontent.com/54778084/233083224-3f2bd11c-1ec4-4d1a-9e3b-7b157d53838a.png)

**Comment by ValentaTomas** [comment]
Hey @SnoopyDevelops this is a problem with setting terminal env vars on Windows.

Running e2b with [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) should solve this but if you want you can try adding https://www.npmjs.com/package/cross-env to make it work on Windows without WSL.

I think these lines are the problem and adding cross-env there would resolve this error:
https://github.com/e2b-dev/e2b/blob/961ece0e6c5cf8d96748bad6069449531b5c4239/package.json#L11
https://github.com/e2b-dev/e2b/blob/961ece0e6c5cf8d96748bad6069449531b5c4239/api-service/playground/nodemon.json#L14

**Comment by SnoopyDevelops** [comment]
It worked!

**Comment by SnoopyDevelops** [comment]
It worked!
