### ISSUE TITLE
e2b build error fail

### ISSUE THREAD

**Issue by dev-kompas** [e2b-dev/E2B#282]
<img width="720" alt="WechatIMG889" src="https://github.com/e2b-dev/E2B/assets/155621604/d87385b0-fdad-4646-b628-fcfa80e1f83c">
 in this folder i run  e2b build --name "kompas-base-sandbox-v1" -d Dockerfile 
<img width="1507" alt="WechatIMG890" src="https://github.com/e2b-dev/E2B/assets/155621604/edbf53de-5aef-4e30-966c-cf287e93dc41">

# this is my Dockerfile

FROM ubuntu:22.04
RUN apt update \
	&& apt install sudo
user root
RUN type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
	&& sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y

RUN apt-get install -y \
    fonts-arphic-uming \
    fonts-nanum \
    fonts-noto-cjk

RUN sudo apt-get install portaudio19-dev -y
RUN sudo apt-get install python3-dev -y
COPY e2b_requirements.txt /opt/
RUN apt-get install python3-pip -y
RUN sudo -H pip3 install --upgrade pip
RUN pip3 cache purge

RUN pip3 install -r /opt/e2b_requirements.txt -i https://pypi.douban.com/simple

# this is my  e2b_requirements.txt

pandas
numpy
scipy
xarray
torch
nltk
spacy
textblob
matplotlib
plotly
requests
urllib3
aiohttp
beautifulsoup4
pillow
imageio
opencv-python
librosa
xlrd
pyPDF2
python-docx
flask
django
tornado

**Comment by mlejva** [comment]
We solved this by increasing the maximum docker image size
