### ISSUE TITLE
JS/TS GitHub Developer - submission #2

### ISSUE THREAD

**Issue by tizkovatereza** [e2b-dev/E2B#294]

**Comment by neo773** [comment]
Could you clarify the issue?

**Comment by ibishal** [comment]
can yu give some more details

**Comment by tizkovatereza** [comment]
@neo773 hello, this is an issue created specifically for a particular user, sorry for confusion. can you please cancel your attempt? thank you!

**Comment by neo773** [comment]
@tizkovatereza Done

**Comment by neo773** [comment]
@dbmanifest 
claim should be in a PR body for Algora bot to detect it, you could make a dummy PR or other alter is the maintainer could tip you with /tip command

**Comment by rajdip-b** [comment]
@tizkovatereza hey there, you can always do a `/tip` to the user. so in case you dont want anyone attempting it, that may be a better alternative! This helps in clarity :D
