### ISSUE TITLE
Use local Docker instance when building custom sandboxes

### ISSUE THREAD

**Issue by mlejva** [e2b-dev/E2B#317]
Currently, when a user runs `e2b build` we upload the Docker context to our backend and build the image there.

This bring several drawbacks like slowness, bad DX because we don't support multi-stage builds or private images, and requirement from us to manage this whole service.

Instead, we should let users to build their images locally (or in CI).

We would have two commands (naming can change):
1. `e2b build` - builds the image locally and pushes it to our backend
2. `e2b push <docker-image-specifier>`- pushes the image to our backend

**Comment by jakubno** [comment]
Solved by https://github.com/e2b-dev/infra/pull/103
