### ISSUE TITLE
Add a way to consume sandbox specific logs via CLI

### ISSUE THREAD

**Issue by mlejva** [e2b-dev/E2B#325]
There's no way to inspect logs for a specific sandbox at the moment. Eventually, there'll be way to inspect logs in our dashboard.

In the meantime, we can build a way to consume logs via our CLI much faster.

### How it would work
Running the following command:
```
e2b sandbox logs <sandbox-id>
```
will display a live stream of logs coming from the sandbox. If the sandbox is already killed, it's still a stream but no new logs are coming in.

### Questions
- How to filter logs based on a date range?
- How much into the past can logs go?

**Comment by mlejva** [comment]
Related PR #327

**Comment by ValentaTomas** [comment]
This feature was added with the PR merge.
