### ISSUE TITLE
Remove the OpenAI integration

### ISSUE THREAD

**Issue by mlejva** [e2b-dev/E2B#347]
The SDK contains an old OpenAI integration that's not being used anymore

JavaScript
https://github.com/e2b-dev/E2B/blob/main/packages/js-sdk/src/templates/openai.ts

Python
https://github.com/e2b-dev/E2B/blob/13c778becbc0fceb940a005528ae89338366a9fb/packages/python-sdk/e2b/sandbox/main.py#L216

**Comment by ValentaTomas** [comment]
The integration was removed.
