### ISSUE TITLE
Add notification in SDK for uploaded files

### ISSUE THREAD

**Issue by ValentaTomas** [e2b-dev/E2B#353]
When you upload a file via URL on the frontend you have to manually call your backend if you want to react there to this event.

We could have a hook/callback in the SDK that automatically creates these sandbox-related notifications.

This hook could be either an instance or class method:

1. As instance method — requiring you to have a sandbox connection:
```ts
sandbox.filesystem.onFileUpload((path) => {})
```
This could be implemented via watchDir functionality relatively easily.

2. As a class method — this would allow you to have the hook without a sandbox connection:
```ts
Sandbox.onFileUpload(sandboxID, (path) => {})
```
Implementing this is noticeably harder — it would require us to have a notification system/infra and changes to the `envd` to allow forwarding events to this system.

---

The current solution is for example to call the server from the frontend after POSTing to the fileURL, or POSTing to the server and calling `sandbox.uploadFile` from there.

**Comment by sarfarazsiddiquii** [comment]
@ValentaTomas I would like to work on this issue. 
Can you assign me?

**Comment by ValentaTomas** [comment]
Duplicate of https://github.com/e2b-dev/E2B/issues/291
