### ISSUE TITLE
`sandbox.cwd` should always return a valid path

### ISSUE THREAD

**Issue by mlejva** [e2b-dev/E2B#354]
Currently `sandbox.cwd` can return string or none/undefined but that don't make sense because even if a developer doesn't set cwd manually, all operations are happening in the `/` path.

So by default sandbox.cwd should return `/`.

**Comment by Mrsatheeth6067** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <form action="registration_process.php" method="post">
            <h2>Register</h2>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>

**Comment by Mrsatheeth6067** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Browser</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="browser">
        <input type="text" id="urlInput" placeholder="Enter URL">
        <button onclick="navigate()">Go</button>
        <iframe id="browserFrame" src="" frameborder="0"></iframe>
    </div>

    <script src="script.js"></script>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}

#browser {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-top: 20px;
}

#urlInput {
    width: 300px;
    padding: 5px;
    margin-bottom: 10px;
}

button {
    padding: 5px 10px;
    cursor: pointer;
}

#browserFrame {
    width: 800px;
    height: 500px;
}

function navigate() {
    var urlInput = document.getElementById('urlInput');
    var browserFrame = document.getElementById('browserFrame');
    var url = urlInput.value;

    if (url.trim() !== '') {
        browserFrame.src = url;
    }
}

</body>
</html>

**Comment by Mrsatheeth6067** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> web browser </title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="coatCounter">
        <p>Coat Count: <span id="count">0</span></p>
        <button onclick="incrementCount()">Increment</button>
        <button onclick="resetCount()">Reset</button>
    </div>

    <script src="script.js"></script>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}

#coatCounter {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-top: 20px;
}

button {
    padding: 5px 10px;
    cursor: pointer;
}
var count = 0;

function incrementCount() {
    count++;
    updateCount();
}

function resetCount() {
    count = 0;
    updateCount();
}

function updateCount() {
    var countElement = document.getElementById('count');
    countElement.textContent = count;
}


</body>
</html>

**Comment by ValentaTomas** [comment]
The new beta SDK does not have the `.cwd` on the sandbox because of subtle bugs (like this) and because we wanted it as stateless as possible.
