### ISSUE TITLE
Can I run the sandbox locally without using cloud?

### ISSUE THREAD

**Issue by maxkoretskyi** [e2b-dev/E2B#381]
### Discussed in https://github.com/orgs/e2b-dev/discussions/378

<div type='discussions-op-text'>

<sup>Originally posted by **maxkoretskyi** May 30, 2024</sup>
Hey! The landing page says:

> open source secure sandboxes for AI-generated code execution

so I thought I could run the sandbox locally without using cloud account. It seems to be not possible. So what does `open-source` mean in the context of `e2b`?
</div>

**Comment by mlejva** [comment]
Hey @maxkoretskyi and sorry for the late response.

E2B needs specific Linux kernel to run so running it for example on your local MacBook doesn't make that much sense. We're focused on making it easy to self-host it on your AWS, GCP account, and then later on general Linux machines.

> So what does open-source mean in the context of e2b?

Everything is open source. From our SDKs, CLI, to infra. Our next step is to make it easy to self-host it.

**Comment by ValentaTomas** [comment]
Also, duplicate of https://github.com/e2b-dev/E2B/issues/239
