### ISSUE TITLE
e2b auth login failed with access token

### ISSUE THREAD

**Issue by qingyuan18** [e2b-dev/E2B#388]
**Describe the bug**
it hungs during the login process , with access key setup in envirement or export it 

**To Reproduce**
(pytorch) ubuntu@ip-172-31-1-180:~/e2b-cookbook/examples/anthropic-power-artifacts$ export E2B_ACCESS_TOKEN=***** && e2b auth login
Attempting to login...

I use  access token so there should not be no brower opened , is it always open browers to login even if I set the env params?

**Desktop (please complete the following information):**

Node.js v20.15.0
yarn install v1.22.22
python 3.10
linux Ubuntu 20.22

**Comment by ValentaTomas** [comment]
Hey, @qingyuan18, the `E2B_ACCESS_TOKEN=***** e2b ...` is used directly for calling commands like `E2B_ACCESS_TOKEN=***** e2b template build` without having to use the `e2b auth login` not for using it to log in.

**Comment by ValentaTomas** [comment]
Hey @qingyuan18 is everything working now?

**Comment by qingyuan18** [comment]
yes, it's working now , Thanks for the support

BTW: we have modified the interactive type to render generated js code directly without sandbox, that's more convient for demo/workshop

will raise for PR for code merge

**Comment by mlejva** [comment]
Good to hear it's working @qingyuan18, the PR would be very welcome!
