### ISSUE TITLE
Crashed when I hit enter on this prompt

### ISSUE THREAD

**Issue by spullara** [e2b-dev/e2b#4]
![image](https://user-images.githubusercontent.com/33424/229905897-2ab86819-9003-4a38-9b5c-06a6feafe0d0.png)

**Comment by ValentaTomas** [comment]
Thank you for reporting it, I'll check it out.

**Comment by ValentaTomas** [comment]
Should be fixed with the [latest](https://github.com/e2b-dev/e2b/commit/e3eacc3c0f573b8a712d3b6dc86803a23e21ac43) commit on `master`.
