### ISSUE TITLE
login in terminal

### ISSUE THREAD

**Issue by binhe22** [e2b-dev/E2B#415]
Then use the CLI like this: E2B_ACCESS_TOKEN=sk_e2b_... e2b build
----

Firstly to be honest, I don't know how to use it after reading it.
So how can I use it ...

Secondly, I think the way tailscale using is more friendly. When I login in the terminal, It will give me a link, then I can paste the link in the browser, then I can auth it. Looking forward to iterating it.

Thanks

**Comment by mlejva** [comment]
Hi @binhe22 can you please be more concrete on what do you don’t know how to use it?

**Comment by binhe22** [comment]
sorry, I apologize for the confusion earlier. 

I am running this command on a VPS, it does not have browser.

when I run e2b auth login, it will return:
Attempting to login...

But I can not login

**Comment by mlejva** [comment]
I see. And as I understand it having your access token set in an environment variable `E2B_ACCESS_TOKEN` doesn't work, correct? What's the error message you see in your terminal?

**Comment by binhe22** [comment]
when I run 

echo $E2B_ACCESS_TOKEN
e2b_xx016

I can get the token above,so I think i set the token succesfully(edited the /etc/environment )


when I run 
e2b template build

I will get

Found ./Dockerfile that will be used to build the sandbox template.
jn [Error]: Unauthorized
    at <anonymous> (/usr/local/lib/node_modules/node_modules/.pnpm/openapi-typescript-fetch@1.1.3/node_modules/openapi-typescript-fetch/dist/esm/fetcher.js:151:23)
    at Generator.throw (<anonymous>)
    at c (/usr/local/lib/node_modules/node_modules/.pnpm/openapi-typescript-fetch@1.1.3/node_modules/openapi-typescript-fetch/dist/esm/fetcher.js:5:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  headers: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(5) {
      'content-type' => [Object],
      'date' => [Object],
      'content-length' => [Object],
      'via' => [Object],
      'alt-svc' => [Object]
    },
    [Symbol(headers map sorted)]: null
  },
  url: 'https://api.e2b.dev/templates',
  status: 401,
  statusText: 'Unauthorized',
  data: {
    code: 401,
    message: 'Invalid Access token, try to login again by running `e2b login`. authorization header is malformed'
  }
}

**Comment by mlejva** [comment]
> when I run
> echo $E2B_ACCESS_TOKEN
> e2b_xx016

This looks like an API token, not access token. The access token starts with `sk_e2b_`. Can you please double check it's an access token? You can get your access token [here](https://e2b.dev/dashboard?tab=personal).

**Comment by binhe22** [comment]
You are right,  I have solved it, Thanks a lot

**Comment by mlejva** [comment]
Great to hear! I'm closing this issue as it's resolved

**Comment by binhe22** [comment]
There are 4 suggestions

1. These two Keys are easily confused. Can we provide some hints to the user?
2. "Then use the CLI like this: E2B_ACCESS_TOKEN=sk_e2b_... e2b build" is ambiguous. I kept looking at this sentence trying to understand its meaning, overlooking the fact that the wrong key was used.
3. Can the error message also be returned in a more user-friendly manner? Please provide some suggestions.
4. I still strongly recommend looking at Tailscale's login method in the terminal. I think the user experience is excellent.

I'm very grateful for you providing such a useful tool. I've been absolutely obsessed with this tool recently.

**Comment by mlejva** [comment]
All good points, appreciate it @binhe22. We'll check out Tailscale.

Thank you for kind words. What are you building?

**Comment by binhe22** [comment]
I'm trying to create a demo similar to artifacts, just for fun～～
