### ISSUE TITLE
Improved Footer and SearchBar

### ISSUE THREAD

**Issue by kumarankit999** [e2b-dev/e2b#45]
**Is your feature request related to a problem? Please describe.**

The Footer Was so simple and boring , We can make it attractive/Interactive .
Add a Dark Mode Toggle button above in the Navbar Section to search anything Very Easily.

![image](https://github.com/e2b-dev/e2b/assets/111564362/ac83a202-93fa-4bba-bb00-0173cb3eda9c)

**Comment by ValentaTomas** [comment]
Hey I don't think this is really related to the e2b project itself. When we are updating our landing page we will keep this in mind.

**Comment by Alaaryad** [comment]
Hey I don't think this is really related to the e2b project itself. When we are updating our landing page we will keep this in mind.

**Comment by Alaaryad** [comment]
That's a good idea 💡

**Comment by aashess** [comment]
yeah!
