### ISSUE TITLE
e2b auth login doesn't work

### ISSUE THREAD

**Issue by blixt** [e2b-dev/E2B#459]
**Describe the bug**

I am unable to use `e2b auth login`. I first installed it with `npm i @e2b/cli` as per [the docs](https://e2b.dev/docs/sandbox-template) (and then ran it with `npx @e2b/cli auth login` since I don't know how else that is supposed to work) as well as via `npm i -g @e2b/cli` which is perhaps what was really intended in the docs, running `e2b auth login` as described.

In both cases they open my browser which shows a dialog to authorize the CLI which appears to work but back in the terminal I get this error:

```
e2b auth login
Attempting to log in...
/opt/homebrew/lib/node_modules/@e2b/cli/src/utils/errors.ts:38
  throw new E2BRequestError(
        ^


Bm [E2BRequestError]: Error getting teams: [401] unauthorized: Invalid Access token, try to login again by running `e2b login`. authorization header is missing
    at handleE2BRequestError (/opt/homebrew/lib/node_modules/@e2b/cli/src/utils/errors.ts:38:9)
    at e.<anonymous> (/opt/homebrew/lib/node_modules/@e2b/cli/src/commands/auth/login.ts:47:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.9.0
```

**Desktop**

- OS: macOS Sequoia 15.0.1
- Browser: Chrome 129

**Comment by mlejva** [comment]
Hi, can you try upgrading the CLI to the latest version? This issue should be fixed now
