### ISSUE TITLE
No downloading of files from sandbox possible, Type error "a bytes-like object is required, not 'str'" occuring

### ISSUE THREAD

**Issue by sopfi** [e2b-dev/E2B#466]
The following code results in the following error message.
Code:
 self.code_interpreter = Sandbox(timeout=300)
 file_in_bytes = self.code_interpreter.files.read('/home/user/' + file_name)
    with open(f"/{trg_file_directory}/{file_name}","wb") as f:
      f.write(file_in_bytes)

Error Message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-267-42746f6edfb7>](https://localhost:8080/#) in <cell line: 2>()
      1 #code_interpreter.download_file(trg_file_directory="content/test",file_name="BoostAndSlowPattern0.PNG")
----> 2 code_interpreter.download_file(trg_file_directory="content/test",file_name="testE2B.txt")

[<ipython-input-262-f34e3d788cf8>](https://localhost:8080/#) in download_file(self, trg_file_directory, file_name)
    256         file_in_bytes = self.code_interpreter.files.read(uploaded_file['remotepath'].path)
    257         with open(f"/{trg_file_directory}/{file_name}","wb") as f:
--> 258           f.write(file_in_bytes)

TypeError: a bytes-like object is required, not 'str'

**Comment by ValentaTomas** [comment]
Hey, @sopfi I think you need to specify the format for the returned data — by default it is string and you are then trying to write bytes to the files.

The following code should work:
```py
import logging

from e2b import Sandbox

import dotenv

dotenv.load_dotenv()

logging.basicConfig(level=logging.ERROR)


sandbox = Sandbox(timeout=300)
file_in_bytes = sandbox.files.read("/.e2b", format="bytes") # Here we specify we want to return bytes.

with open(f"e2b-downloaded-file", "wb") as f:
    f.write(file_in_bytes)

sandbox.kill()
```

**Comment by sopfi** [comment]
Hi @ValentaTomas,
thanks so much for your quick help. The attribute "format = bytes" fixed the problem!
