### ISSUE TITLE
Fix lights

### ISSUE THREAD

**Issue by Alaaryad** [e2b-dev/e2b#48]
Fix lights

_Originally posted by @Alaaryad in https://github.com/Alaaryad/scaling-engine/issues/7#issuecomment-1553859489_

**Comment by ValentaTomas** [comment]
I'm not sure what you are talking about. If you explain in more detail I'll reopen the issues.

**Comment by Alaaryad** [comment]
I'm not sure what you are talking about. If you explain in more detail I'll reopen the issue.
