### ISSUE TITLE
To help with documentation in the future, please use "WCAG 3" (instead of "WCAG 3.0") in most places.

### ISSUE THREAD

**Issue by Tamarahill** [e2b-dev/e2b#49]
To help with documentation in the future, please use "WCAG 3" (instead of "WCAG 3.0") in most places.

> Use "WCAG 3" in most cases; e.g., [WCAG 3 Introduction](https://www.w3.org/WAI/standards-guidelines/wcag/wcag3-intro/).
> Can use WCAG 3.0 for references to the TR doc.
https://www.w3.org/WAI/EO/wiki/Style#Referring_to_xxAG_.28WCAG_2.3B_singular.29

Let me know if questions or suggestions for amending that. Thanks!

_Originally posted by @shawna-slh in https://github.com/w3c/silver/issues/692_

**Comment by ValentaTomas** [comment]
I'm not sure what you are talking about. If you explain in more detail I'll reopen the issue.

**Comment by Alaaryad** [comment]
Explain to me

**Comment by Alaaryad** [comment]
WCAG3

**Comment by Alaaryad** [comment]
WCAG 3
