### ISSUE TITLE
JS SDK - wait for a port to open 

### ISSUE THREAD

**Issue by anton-series** [e2b-dev/E2B#513]
**Is your feature request related to a problem? Please describe.**

I'm using a custom Next.js template which is cloned from your nextjs-developer template, but uses app router.

The Next server takes around 3-5 seconds to start. 

However, the JS SDK returns the hostname of the sandbox too early, while the server has not started yet. 

As a result, I am seeing a 502 Bad Gateway error when loading the page. If I reload the page 3-5 seconds later, it works. 

**Describe the solution you'd like**

When creating a sandbox, provide a method to wait until a port opens, like:

```
    const sandbox = await Sandbox.create(E2B_TEMPLATE_ID, {
      apiKey: env.e2bApiKey,
    });
    
    await sandbox.ports.waitForOpen(3000);
```

**Comment by mishushakov** [comment]
Hey!
The JS SDK is working as expected. You can implement it yourself, however like this:

healthcheck.py

```py
import requests
import time
import sys

def check_server(url: str):
    max_attempts = 20
    sleep_time = 1 # in seconds

    for attempt in range(max_attempts):
        try:
            response = requests.get(url)
            if response.status_code == 200:
                print(f"Server is up after {attempt + 1} attempts.")
                return True
        except requests.RequestException:
            pass

        print(f"Attempt {attempt + 1} failed. Retrying in {sleep_time} seconds...")
        time.sleep(sleep_time)

    print(f"Server did not respond with 200 status code after {max_attempts} attempts.")
    return False

if __name__ == "__main__":
    url = sys.argv[1]

    print(f"Checking server at {url}")
    check_server(url)
```

in Dockerfile:

```
COPY healthcheck.py /home/user/healthcheck.py
```

before returning the hostname:

```
await sbx.commands.run(
  `python3 /home/user/healthcheck.py http://localhost:${port}`,
);
```
