### ISSUE TITLE
Internal Server Request in the homepage after following setup instructions

### ISSUE THREAD

**Issue by baristaGeek** [e2b-dev/e2b#54]
**Describe the bug**
I followed the setup instructions. When running on localhost` /settings` works but` /` doesn't. 

**To Reproduce**
1. npm start on terminal window 1. And then once it finishes building:
2. npm run dev on terminal window 2
3. go to localhost:3000
4. Insert my open ai api key on the settings screen

**Expected behavior**
I'm expecting to see some sort of welcome UI instead of a 500

**Browser console output**
A client-side exception has occurred, see here for more info
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Terminal commands & output**
e2b-app-1  | prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
e2b-app-1  | Please manually install OpenSSL via `apt-get update -y && apt-get install -y openssl` and try installing Prisma again. If you're running Prisma on Docker, you may also try to replace your base image with `node:lts-slim`, which already ships with OpenSSL installed.
e2b-app-1  | Error: Command failed with exit code 127: /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x --enable-raw-queries cli dmmf
e2b-app-1  | /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
e2b-app-1  |     at makeError (/app/node_modules/@prisma/client/runtime/binary.js:14:57)
e2b-app-1  |     at handlePromise (/app/node_modules/@prisma/client/runtime/binary.js:14:11276)
e2b-app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
e2b-app-1  |     at async Wi._getDmmf (/app/node_modules/@prisma/client/runtime/binary.js:160:2387)
e2b-app-1  |     at async /app/node_modules/@prisma/client/runtime/binary.js:235:2875
e2b-app-1  |     at async /app/node_modules/@prisma/client/runtime/binary.js:235:3305
e2b-app-1  |     at async t._executeRequest (/app/node_modules/@prisma/client/runtime/binary.js:235:10764)
e2b-app-1  |     at async t._request (/app/node_modules/@prisma/client/runtime/binary.js:235:10493)
e2b-app-1  |     at async /app/.next/server/pages/index.js:217:18 {
e2b-app-1  |   shortMessage: 'Command failed with exit code 127: /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x --enable-raw-queries cli dmmf',

**Screenshots**
https://github.com/e2b-dev/e2b/assets/8325094/86f5667c-1164-444c-890a-605c05aa42ae

**Desktop (please complete the following information):**
 - OSX
 - Chrome
 - Node 18.9.0

**Additional context**
I did change my Supabase keys to the ones generated after running `npm run db:start`

**Comment by ValentaTomas** [comment]
Hi, thanks for opening an issue.

The SSL Prisma error should be a problem only with Docker sometimes (e2b started via `npm start`) if you follow the [Development Setup](https://github.com/e2b-dev/e2b/blob/main/DEVELOPMENT_SETUP.md) it should not be a problem.

Also the `npm start` and `npm run dev` commands are not intended to be used at the same time - `npm start` is for running the whole setup via Docker and `npm run dev` for just running the e2b in a dev mode (but you need to install all the deps before with `npm run install:all).

If you started the setup via `npm start` you may have to stop it by `npm run stop` before using the Development Setup.

**Comment by baristaGeek** [comment]
Ahh that's it! They are not intended to be used at the same time. Thanks!
