### ISSUE TITLE
Unsupported provider

### ISSUE THREAD

**Issue by pvtrn** [e2b-dev/e2b#60]
{"code":400,"msg":"Unsupported provider: provider is not enabled"}

Not working GitHub signin button after install and first visit.

**Comment by mlejva** [comment]
Hi @paveltaran this looks like an issue we've been [discussing on our Discord](https://discord.com/channels/1092455714431180995/1125878637795750030/1125878637795750030).

It's a problem with our local setup that isn't ideal at the moment. We're working on it. Thank you for reporting

**Comment by mlejva** [comment]
Hey @Strajk, this indeed should be the "solution". Sorry for this roadblock! We thought by sharing different envs with it should've been fixed
