### ISSUE TITLE
Yarn Install Errors

### ISSUE THREAD

**Issue by KochMartin** [e2b-dev/e2b#8]
Got a few errors from yarn during the initial clean install. Not familiar with yarn, looking for help.
Here is what I did incl. terminal output. Running on a M1 

_**I checked the requirements first, seems fine:**_ 

Docker -v
Docker version 20.10.23, build 7155243

poetry -V
Poetry (version 1.4.2)

node -v
v18.12.1

python -V
Python 3.11.2

yarn -v
3.5.0

-----------------------------------------------------------------------------------------------

_**Then I fetch a fresh clone of the repo.**_

gh repo clone e2b-dev/e2b
Cloning into 'e2b'...
remote: Enumerating objects: 5913, done.
remote: Counting objects: 100% (577/577), done.
remote: Compressing objects: 100% (298/298), done.
remote: Total 5913 (delta 289), reused 522 (delta 271), pack-reused 5336
Receiving objects: 100% (5913/5913), 3.20 MiB | 9.78 MiB/s, done.
Resolving deltas: 100% (3920/3920), done.

-----------------------------------------------------------------------------------------------

cd e2b

_**Starting with the first yarn command. It has a problem and recommends to run "yarn install instead" which I did.**_

yarn install:all

Internal Error: ai-api@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (/Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:435:5145)
    at xf.getCandidates (/Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:391:1264)
    at /Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:439:7693
    at ff (/Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:390:11070)
    at ge (/Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:439:7673)
    at async Promise.allSettled (index 0)
    at async to (/Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:390:10398)
    at async /Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:439:8205
    at async ti.startProgressPromise (/Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:390:47579)
    at async je.resolveEverything (/Users/martin/.cache/node/corepack/yarn/3.5.0/yarn.js:439:6233)

-----------------------------------------------------------------------------------------------

_**It has a problem and recommends to run "yarn install instead" which I did.**_

yarn install
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍

➤ YN0000: ┌ Resolution step
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0032: │ bufferutil@npm:4.0.7: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ utf-8-validate@npm:5.0.10: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (pb8aea), requested by @tiptap/core
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (pec51a), requested by @tiptap/extension-code-block
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (p15c05), requested by @tiptap/extension-dropcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (p4a73e), requested by @tiptap/extension-gapcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (p84589), requested by @tiptap/extension-history
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (pc2d7d), requested by @tiptap/extension-horizontal-rule
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 10s 470ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yaml@npm:1.10.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zustand@npm:4.3.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 440ms
➤ YN0000: ┌ Link step
➤ YN0007: │ supabase@npm:1.46.5 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/engines@npm:4.11.0 must be built because it never has been before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.7 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.10 must be built because it never has been before or the last one failed
➤ YN0007: │ prisma@npm:4.11.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/client@npm:4.11.0 [556c3] must be built because it never has been before or the last one failed
➤ YN0007: │ ai-api@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 9s 298ms
➤ YN0000: Done with warnings in 20s 277ms

-----------------------------------------------------------------------------------------------

_**Trying to use install:all again to make sure nothing was missed.**_

yarn install:all
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (pb8aea), requested by @tiptap/core
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (pec51a), requested by @tiptap/extension-code-block
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (p15c05), requested by @tiptap/extension-dropcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (p4a73e), requested by @tiptap/extension-gapcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (p84589), requested by @tiptap/extension-history
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.220 doesn't provide @tiptap/pm (pc2d7d), requested by @tiptap/extension-horizontal-rule
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 387ms
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: codegen (0.1.0)
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ utf-8-validate@npm:5.0.10: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ bufferutil@npm:4.0.7: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0000: └ Completed in 7s 761ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yaeti@npm:0.0.6 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yamljs@npm:0.3.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 267ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.17.11 must be built because it never has been before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.7 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.10 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 3s 281ms
➤ YN0000: Done with warnings in 11s 351ms

-----------------------------------------------------------------------------------------------

_**Ok, seems fine now. Let's try the next step.**_

yarn db:start
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/martin/Code/e2b/node_modules/supabase/bin/supabase. Loading extensionless files is not supported inside of "type":"module" package.json contexts. The package.json file /Users/martin/Code/e2b/node_modules/supabase/package.json caused this "type":"module" context. Try changing /Users/martin/Code/e2b/node_modules/supabase/bin/supabase to have a file extension. Note the "bin" field of package.json can point to a file with an extension, for example {"type":"module","bin":{"supabase":"./bin/supabase.js"}}
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v18.12.1

_**Got a stacktrace and no idea where I went wrong ...**_

Anyone got a idea how to solve this?

**Comment by jzanecook** [comment]
> yarn -v 3.5.0

Mine is running on yarn version 1.22.19, which is the "Classic Stable" version on https://classic.yarnpkg.com/lang/en/ 

Could that be the issue?

**Comment by KochMartin** [comment]
That's it! Thanks a lot!
It was quite a struggle to activate the right Yarn version as I had multiple installs along the way, but switching to your version solved the issue. 

Thanks again :)
