### ISSUE TITLE
NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by 4A49** [e2b-dev/e2b#9]
![image](https://user-images.githubusercontent.com/115742777/230201317-0d709657-f9e8-4ad5-898f-bb5719eb5282.png)

I am unable to move past this.

**Comment by mlejva** [comment]
Hey, can you please do the following
1. Post your terminal output here
2. Post output from your Chrome Developer Tools console

Thanks

**Comment by ValentaTomas** [comment]
Can you `git pull` on master and try starting the project with the [new instructions](https://github.com/e2b-dev/e2b#get-started)? 
We added a way to start the app via Docker to solve a lot of dependency and connection issues people had.

You essentially just need to do the two steps:

## 1. Add env var
Create .env file by copying the [.env.example](https://github.com/e2b-dev/e2b/blob/master/.env.example)
```
cp .env.example .env
```
and fill in the following variable:
- OPENAI_API_KEY - your [OpenAI key](https://platform.openai.com/account/api-keys)

## 2. Start the app
```
npm start
```
Then open the page on http://localhost:3000/.

**Comment by Q-efx** [comment]
It shows this error:

ws://78.47.67.96:3000/_next/webpack-hmr

NS_ERROR_CONNECTION_REFUSED

http://localhost:54321/auth/v1/token?grant_type=password

CORS failed

**Comment by Bnjoroge1** [comment]
Do you have any firewalls that might be blocking the WebSocket connection? Something is interfering with listening at the websocket.

**Comment by ValentaTomas** [comment]
I'm looking into a possible general fix 👌.

**Comment by ValentaTomas** [comment]
Hey @4A49, there is a new update on `master` - we are now proxying all requests so a lot of network issues should be now resolved. Check it out!

**Comment by mlejva** [comment]
Closing this issue as it should be resolved on the `main` branch. @4A49 please let us know to reopen this or create a new issue if the problems persist.
